# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4959cb203732381f6d82919a9b907da98580502f7935b40999106771537bf3a2883718a41ab64341da6e5b5385225158965eda09d2279b081225ef5c65d3fc

test:
  secret_key_base: 4ba62cfe360b30f850f328deb7c65b60505e812ab3f5d53aaeede95127251dc8f4f34e6dad24f76d0c342746abcb1fd742505c8272e1e134971822396df7f8ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
